name: Lint and Type Check

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['main']
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: 📦 Setup Node + Bun + install deps
        uses: ./.github/actions/setup-node-bun-install

      - name: Lint
        run: bun lint

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: 📦 Setup Node + Bun + install deps
        uses: ./.github/actions/setup-node-bun-install

      - name: Lint and type-check
        run: bun typecheck
